### ISSUE TITLE
format of .pkl files in the datasets

### ISSUE THREAD

**Issue by refrantz** [med-air/3DSAM-adapter#11]
Good afternoon,

Could you explain a bit more on the format of the .pkl files? From my understanding, the split.pkl is simply a list with the training images, but what is the prompt.pkl? opening it reveals a dict with name_of_image : MSD/name_of_image, but there is not MSD folder in the dataset, and what is the MSD folder supposed to be? Aside from that, was there any testing done on datasets with more than 2 labels? Such as multi organ segmentation?

Thanks in advance, Renan.

**Comment by peterant330** [comment]
> Good afternoon,
> 
> Could you explain a bit more on the format of the .pkl files? From my understanding, the split.pkl is simply a list with the training images, but what is the prompt.pkl? opening it reveals a dict with name_of_image : MSD/name_of_image, but there is not MSD folder in the dataset, and what is the MSD folder supposed to be? Aside from that, was there any testing done on datasets with more than 2 labels? Such as multi organ segmentation?
> 
> Thanks in advance, Renan.

Hi,

prompt.pkl is not actually used. It is something we used for testing the code. You can just pass None to this parameter. We will clean the code to make it more brief and readable later. 

We haven't tested it for multiple-label segmentation. If the multiple labels are disjoint, I think you can just treat it as binary and use the prompt to distinguish different organs. If they have some overlapping such as lesions and organs, things may be more complicated. We have a very initial idea which is to use different global queries in the prompt encoder to denote different labels. But we haven't achieved impressive performance yet. This is also something worth effort in the future.
