### ISSUE TITLE
Point prompt taken from GT in inference time?

### ISSUE THREAD

**Issue by rafiibnsultan** [med-air/3DSAM-adapter#36]
Hi,
Great work first of all. I have a question, if I understand correctly the point prompt has been taken from GT in inference time right? But, that is not practical for a real-life situation, right? In inference time, we don't have GT, if we had GT what is the point of doing segmentation?

**Comment by setayeshk** [comment]
i have the exact same question too

**Comment by peterant330** [comment]
Hi, 

Taking prompt from the GT is for the evaluation purpose. For a real-life situation, the prompt should be given by a domain expert, which is a common practice for interactive segmentation.

**Comment by rafiibnsultan** [comment]
Hi,

Makes sense.
Thank you for the response.
