### ISSUE TITLE
Does the relative position embedding work?

### ISSUE THREAD

**Issue by 22TonyFStark** [med-air/3DSAM-adapter#5]
Hello, I notice that you provide the code for the relative position as optional,  I wonder have you done some experiments about it? Does it work well?
Thanks for your work, it inspires me a lot :)

**Comment by peterant330** [comment]
> Hello, I notice that you provide the code for the relative position as optional, I wonder have you done some experiments about it? Does it work well? Thanks for your work, it inspires me a lot :)

The code about the relative position is inherited from the original SAM code. As we are focusing on fine-tuning, for those parameters we just use the same setting as the original code without further ablation (which is set to be true if I remember correctly).

**Comment by 22TonyFStark** [comment]
thanks~

> > Hello, I notice that you provide the code for the relative position as optional, I wonder have you done some experiments about it? Does it work well? Thanks for your work, it inspires me a lot :)
> 
> The code about the relative position is inherited from the original SAM code. As we are focusing on fine-tuning, for those parameters we just use the same setting as the original code without further ablation (which is set to be true if I remember correctly).

thanks~
