### ISSUE TITLE
MSD-Colon dataset

### ISSUE THREAD

**Issue by WuJuli** [med-air/3DSAM-adapter#9]
Hi, I can't download your preprocessed dataset using your provided links, could you please fix that?

![72a6c19d093a00eed85cc7cabb448db](https://github.com/med-air/3DSAM-adapter/assets/46019998/62bfd94f-7914-40d4-948a-1e9a9d7fa8ea)

**Comment by peterant330** [comment]
> Hi, I can't download your preprocessed dataset using your provided links, could you please fix that?
> 
> ![72a6c19d093a00eed85cc7cabb448db](https://user-images.githubusercontent.com/46019998/255097527-62bfd94f-7914-40d4-948a-1e9a9d7fa8ea.png)

Hi,

Could you please try again? I think I fixed the issue.

**Comment by WuJuli** [comment]
yes!
